merge_premium =  [
    [
        "ALLIEDBANKERS INSURANCE CORPORATION  -  96",
        "PNB GENERAL INSURERS CO., INC.  -  122"
    ]
]

premium_rename = {
    "ALLIEDBANKERS INSURANCE CORPORATION  -  96": "ALLIED"
}

merge_cashcall = [
    [
        "ALLIEDBANKERS INSURANCE CORPORATION",
        "PNB GENERAL INSURERS CO., INC."
    ],
    [
        "ETIQA LIFE AND GENERAL ASSURANCE PHILIPPINES, INC.",
        "ASIANLIFE & GENERAL ASSURANCE CORPORATION"
    ],
    [
        "JARDINE LLOYD THOMPSON INSURANCE AND REINSURANCE",
        "JLT INS. AND REINS. BROKERS INC."
    ],
    [
        "MEGA RE INTERNATIONAL, INC.",
        "MEGA RE INT'L. INC."
    ],
    [
        "REPUBLIC SURETY & INSURANCE CO., INC."
    ],
    [
        "PANA HARRISON REINSURANCE BROKERS (PHILS.), INC.",
        "PANA HARRISON REINSURANCE BROKERS (PHILS.) INC.",
        "PANA HARRISON REINSURANCE BROKERS (PHILS.),INC."
    ]

]

cashcall_rename = {
    "ALLIEDBANKERS INSURANCE CORPORATION": "ALLIED",
    "ETIQA LIFE AND GENERAL ASSURANCE PHILIPPINES, INC.": "ETIQA",
    "JARDINE LLOYD THOMPSON INSURANCE AND REINSURANCE": "GUY CARPENTER",
    "MEGA RE INTERNATIONAL, INC.": "MEGA RE INTERNATIONAL, INC.",
    "REPUBLIC SURETY & INSURANCE CO., INC.": "M PIONEER",
    "PANA HARRISON REINSURANCE BROKERS (PHILS.),INC.": "PANA HARRISON REINSURANCE BROKERS PHILS INC"
}

